server:  
    port: 7009
    address: localhost
# DATASOURCE  
spring:
    datasource:
             master:
                  name: masterdatabase
                  url: jdbc:mysql://localhost:3306/masterdatabase?characterEncoding=utf-8
                  username: root
                  password: root
                  # 使用druid数据源
                  type: com.alibaba.druid.pool.DruidDataSource
                  driver-class-name: com.mysql.jdbc.Driver
                  filters: stat,log4j
                  maxActive: 20
                  initialSize: 1
                  maxWait: 60000
                  minIdle: 1
                  timeBetweenEvictionRunsMillis: 60000
                  minEvictableIdleTimeMillis: 300000
                  validationQuery: select 'x'
                  testWhileIdle: true
                  testOnBorrow: false
                  testOnReturn: false
                  poolPreparedStatements: true
                  maxOpenPreparedStatements: 20
             slaver:
                  name: slaverdatabase
                  url: jdbc:mysql://localhost:3306/slaverdatabase?characterEncoding=utf-8
                  username: root
                  password: root
                  # 使用druid数据源
                  type: com.alibaba.druid.pool.DruidDataSource
                  driver-class-name: com.mysql.jdbc.Driver
                  filters: stat,log4j
                  maxActive: 20
                  initialSize: 1
                  maxWait: 60000
                  minIdle: 1
                  timeBetweenEvictionRunsMillis: 60000
                  minEvictableIdleTimeMillis: 300000
                  validationQuery: select 'x'
                  testWhileIdle: true
                  testOnBorrow: false
                  testOnReturn: false
                  poolPreparedStatements: true
                  maxOpenPreparedStatements: 20
    